---
name: Clang-format
on:
  pull_request:
    paths:
      - "examples/**"
      - "include/**"
      - "src/**"
  merge_group:
  push:
    paths:
      - "examples/**"
      - "include/**"
      - "src/**"
jobs:
  cancel-runs:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Actions checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run clang format lint
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: "src"
          exclude: "src/protobuf"
          extensions: "cpp,hpp,h"
          clangFormatVersion: 17
          inplace: true

      - name: Run add and commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Code format - (Clang-format)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
